# Monte Carlo Simulation and Linear Algebra

**CS1302 Introduction to Computer Programming**
___

*All the lectures after(including) this week will not be included in final exams*

In [2]:
# set up environment
%reset -f
import sys
cs1302_site_packages = '/home/course/cs1302/site-packages'
if cs1302_site_packages not in sys.path:
    sys.path.append(cs1302_site_packages)
%reload_ext mytutor
import matplotlib.pyplot as pyplot
import ipywidgets as widgets

## Monte Carlo simulation

**What is Monte Carlo simulation?**

 > The name Monte Carlo refers to the [Monte Carlo Casino in Monaco](https://en.wikipedia.org/wiki/Monte_Carlo_Casino) where Ulam's uncle would borrow money from relatives to gamble.

It would be nice to simulate the casino, so Ulam's uncle did not need to borrow money to go.  
Actually...,
- Monte Carlo is the code name of the secret project for creating the [hydrogen bomb](https://en.wikipedia.org/wiki/Monte_Carlo_method). 
- [Ulam](https://en.wikipedia.org/wiki/Stanislaw_Ulam) worked with [John von Neumann](https://en.wikipedia.org/wiki/John_von_Neumann) to program the first electronic computer ENIAC to simulate a computational model of a thermonuclear reaction.

(See also [The Beginning of the Monte Carlo Method](https://permalink.lanl.gov/object/tr?what=info:lanl-repo/lareport/LA-UR-88-9067) for a more detailed account.)

**Some background**

* Deterministic problems 
   * Some problems in science and technology are desrcribed by “exact” mathematics, leading to “precise” results
   * Example: If you run at a speed of 5 m/s, how long does it take to run 100 meters? 
* Stochastic problems
    * Some problems appear physically uncertain
    * Examples: roll a die, flip a coin
    * Use random numbers to mimic the uncertainty of the experiment.

Monte Carlo Simulation
* A method of estimating the value of an unknown quantity using the principles of inferential statistics
* Inferential statistics
   * Population: a set of examples
   * Sample: a proper subset of a population

* Key fact: a random sample tends to exhibit the same properties as the population from which it is drawn

**How to compute the value of $\pi$**?

An even earlier use of Monte Carlo simulation is in approximating $\pi$ using 
the [Buffon's needle](https://en.wikipedia.org/wiki/Buffon%27s_needle_problem).  
There is [a program](https://www.khanacademy.org/computer-programming/pi-by-buffons-needle/6695500989890560) written in javascript to do this.

The javascript program a bit long to digest, so we will use an alternative simulation that is easier to understand/program.

If we uniformly randomly pick a point in a square. What is the chance it is in the inscribed circle, i.e., the biggest circle inside the square?

The chance is the area of the circle divided by the area of the square. Suppose the square has length $\ell$, then the chance is
  $$ \frac{\pi (\ell /2)^2}{ (\ell)^2 } = \frac{\pi}4 $$
independent of the length $\ell$.

**Exercise** Complete the following function to return an approximation of $\pi$ as follows:
1. Simulate the random process of picking a point from a square repeatedly `n` times by  
  generating the $x$ and $y$ coordinates uniformly randomly from a unit interval $[0,1)$.
2. Compute the fraction of times the point is in the first quadrant of the inscribed circle as shown in the figure below.
3. Return $4$ times the fraction as the approximation.
<p><a href="https://commons.wikimedia.org/wiki/File:Pi_30K.gif#/media/File:Pi_30K.gif"><img src="https://upload.wikimedia.org/wikipedia/commons/8/84/Pi_30K.gif" alt="Pi 30K.gif"></a></p>

In [126]:
import random, math

def approximate_pi(n):
    ### BEGIN SOLUTION
     return 4*len([True for i in range(n) 
                   if random.random()**2 + random.random()**2 < 1])/n
    ### END SOLUTION
print(f'Approximate: {approximate_pi(int(1e7))}\nGround truth: {math.pi}')

Approximate: 3.141238
Ground truth: 3.141592653589793


**How accurate is the approximation?**

The following uses a powerful library `numpy` for computing to return a [$95\%$-confidence interval](http://onlinestatbook.com/2/estimation/mean.html#:~:text=To%20compute%20the%2095%25%20confidence,be%20between%20the%20cutoff%20points.).

In [127]:
import numpy as np

def np_approximate_pi(n):
    in_circle = (np.random.random((n,2))**2).sum(axis=-1) < 1
    mean = 4 * in_circle.mean()
    std = 4 * in_circle.std() / n**0.5
    return np.array([mean - 2*std, mean + 2*std])

interval = np_approximate_pi(int(1e7))
print(f'''95%-confidence interval: {interval}
Estimate: {interval.mean():.4f} ± {(interval[1]-interval[0])/2:.4f}
Ground truth: {math.pi}''')

95%-confidence interval: [3.14094356 3.14302044]
Estimate: 3.1420 ± 0.0010
Ground truth: 3.141592653589793


Note that the computation done using `numpy` is over $5$ times faster despite the additional computation of the standard deviation.

There are faster methods to approximate $\pi$ such as the [Chudnovsky_algorithm](https://en.wikipedia.org/wiki/Chudnovsky_algorithm), but Monte-Carlo method is still useful in more complicated situations.   
E.g., see the Monte Carlo simulation of a [real-life situation](https://www.youtube.com/watch?v=-fCVxTTAtFQ) in playing basketball:
> "when down by three and left with only 30 seconds is it better to attempt a hard 3-point shot or an easy 2-point shot and get another possession?"   --Lebron James

**A short summary**
1. What is Monte Carlo simulation and the process of Monte Carlo simulation.

## Linear Algebra

**Matrices**

A matrix is a rectangular array of numbers
$$\left[ \begin{array}{cccc}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8 \\
9 & 10 & 11 &12
\end{array} \right] $$
* its size is given by (row dimension) $\times$ (column dimension) e.g., matrix above is 3 $\times$ 4
* *elements* also called *entries* or *coefficients*

Index
* $A_{i,j}$ is $i$, $j$ element of matrix $A$
* $i$ is the row index, $j$ is the column index

Matrix equality
* two matrices are equal (denoted with =) if they are the same size and corresponding entries are equal

**Column and row vectors**

* a $1 \times n$ matrix is called a row vector $[$ 1  2 3$]$

* a $n \times 1$ matrix is called a column vector $\left[ \begin{array}{c} 1\\ 5\\ 9 \end{array}\right]$

Suppose $A$ is an $m \times n$ matrix with entries $A_{i,j}$ for $i = 1,\cdots, m$, $j = 1, \cdots, n$

* its $i$-th row vector is (a n-vector): $[A_{i,1} A_{i,2} \cdots A_{i,n}]$


* its $j$-th column vector is (a m-vector): $\left[ \begin{array}{c} A_{1,j}\\ A_{2,j}\\ \vdots \\ A_{m,j} \end{array}\right]$


**Addition, subtraction**

* (just like vectors) we can add or subtract matrices of the same size:
$$(A + B)_{i,j} = A_{i,j} + B_{i,j}$$
$$(A - B)_{i,j} = A_{i,j} - B_{i,j}$$
* Example:
$$\left[ \begin{array}{cccc}
1 & 2 & 3\\
4 & 5 & 6 \\
7 & 8 & 9
\end{array} \right] + \left[ \begin{array}{cccc}
9 & 8 & 7\\
6 & 5 & 4 \\
3 & 2 & 1
\end{array} \right] = \left[ \begin{array}{cccc}
10 & 10 & 10\\
10 & 10 & 10 \\
10 & 10 & 10
\end{array} \right]$$

**Matrices multiplication**

* scalar multiplication is easy: $ \alpha A = \alpha A_{i,j}$
* For example:
$$2 \cdot \left[ \begin{array}{cccc}
1 & 2 & 3\\
4 & 5 & 6 \\
7 & 8 & 9
\end{array} \right] = \left[ \begin{array}{cccc}
2 & 4 & 6\\
8 & 10 & 12 \\
14 & 16 & 18
\end{array} \right]$$

* But to multiply a matrix by another matrix we need to do the "dot product" of rows and columns
* $A$ is an $m \times n$ matrix and B is an $n \times p$ matrix:
$$A=\left[ \begin{array}{cccc}
a_{11} & a_{12} & \cdots & a_{1n}\\
a_{2,1} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots  &\ddots & \vdots \\
a_{m1} & a_{m2}& \vdots & a_{mn}
\end{array} \right] B=\left[ \begin{array}{cccc}
b_{11} & b_{12} & \cdots & b_{1p}\\
b_{2,1} & b_{22} & \cdots & b_{2p} \\
\vdots & \vdots  &\ddots & \vdots \\
b_{n1} & b_{n2}& \vdots & b_{np}
\end{array} \right]$$

then 
$$C= AB = \left[ \begin{array}{cccc}
c_{11} & c_{12} & \cdots & c_{1p}\\
c_{2,1} & a_{22} & \cdots & c_{2p} \\
\vdots & \vdots  &\ddots & \vdots \\
c_{m1} & c_{m2}& \vdots & c_{mp}
\end{array} \right]$$ where $C_{ij}=\sum\limits_{k=1}^{n} a_{ik} b_{kj}$

* More details can be found [here](https://www.mathsisfun.com/algebra/matrix-multiplying.html).

**Matrix division**

* We don't actually divide matrices, we do it this way:
$$ A / B = A \times (1/B) = A \times B^{-1} $$
  where $B^{-1}$ means the "inverse" of $B$.

So we don't divide, instead we multiply by an inverse.

And there are special ways to find the inverse, learn more from [here](https://www.mathsisfun.com/algebra/matrix-inverse.html).


**How to solve a linear equation?**

Given the following linear equation in variable $x$ with real-valued coefficient $a$ and $b$,
$$ a x = b,$$
what is the value of $x$ that satisfies the equation?

**Exercise** Complete the following function to return either the unique solution of $x$ or None if it does not exist.

In [171]:
def solve_linear_equation(a,b):
    ### BEGIN SOLUTION
    return b/a if a != 0 else None
    ### END SOLUTION

import ipywidgets as widgets
@widgets.interact(a=(0,5,1),b=(0,5,1))
def linear_equation_solver(a=2, b=3):
    print(f'''linear equation: {a}x = {b}
       solution: x = {solve_linear_equation(a,b)}''')

interactive(children=(IntSlider(value=2, description='a', max=5), IntSlider(value=3, description='b', max=5), …

**How to solve multiple linear equations?**

In the general case, we have a system of $m$ linear equations and $n$ variables:
$$ \begin{aligned}
a_{00} x_0 + a_{01} x_1 + \dots + a_{0(n-1)} x_{n-1} &= b_0\\
a_{10} x_0 + a_{11} x_1 + \dots + a_{1(n-1)} x_{n-1} &= b_1\\
\vdots\kern2em &= \vdots\\
a_{(m-1)0} x_0 + a_{(m-1)1} x_1 + \dots + a_{(m-1)(n-1)} x_{n-1} &= b_{m-1}\\
\end{aligned}$$
where
- $x_j$ for $j\in \{0,\dots,n-1\}$ are the variables, and
- $a_{ij}$ and $b_j$ for $i\in \{0,\dots,m-1\}$ and $j\in \{0,\dots,n-1\}$ are the coefficients.

A fundamental problem in linear algebra is to compute the unique solution to the system if it exists.

We will consider the simpler 2-by-2 system with 2 variables and 2 equations:
$$ \begin{aligned}
a_{00} x_0 + a_{01} x_1 &= b_0\\
a_{10} x_0 + a_{11} x_1 &= b_1
\end{aligned}$$

To get an idea of the solution, suppose 
$$a_{00}=a_{11}=1, a_{01} = a_{10} = 0.$$
The system of equations become
$$ \begin{aligned}
x_0 \hphantom{+ x_1} &= b_0\\
\hphantom{x_0 +}  x_1 &= b_1,
\end{aligned}$$
which gives the solution directly.

What about $a_{00}=a_{11}=2$ instead?
$$ \begin{aligned}
2x_0 \hphantom{+ x_1} &= b_0\\
\hphantom{2x_0 +}  2x_1 &= b_1,
\end{aligned}$$

To obtain the solution, we simply divide both equations by 2:
  $$ \begin{aligned}
x_0 \hphantom{+ x_1} &= \frac{b_0}2\\
\hphantom{x_0 +}  x_1 &= \frac{b_1}2.
\end{aligned}$$

What if $a_{01}=2$ instead?
$$ \begin{aligned}
2x_0 + 2x_1 &= b_0\\
\hphantom{2x_0 +}  2x_1 &= b_1\\
\end{aligned}$$

The second equation gives the solution of $x_1$, and we can use the solution in the first equation to solve for $x_0$. More precisely:
- Subtract the second equation from the first one:
$$ \begin{aligned}
2x_0 \hphantom{+2x_1} &= b_0 - b_1\\
\hphantom{2x_0 +}  2x_1 &= b_1\\
\end{aligned}$$
- Divide both equation by 2:
$$ \begin{aligned}
x_0 \hphantom{+ x_1} &= \frac{b_0 - b_1}2\\
\hphantom{x_0 +}  x_1 &= \frac{b_1}2\\
\end{aligned}$$

The above operations are called *row operations* in linear algebra: each row is an equation.  
A system of linear equations can be solved by the linear operations of 
1. multiplying an equation by a constant, and
2. subtracting one equation from another.

How to write a program to solve a general 2-by-2 system? We will use the `numpy` library.
* It stands for '*Numerical Python*'

**Why Numpy?**
* Python does numerical computations slowly.
* 1000 $\times$ 1000 matrix multiply
   * Python triple loop takes > 10 min.
   * Numpy takes ~0.03 seconds
* Using NumPy, a developer can perform the following operations:
   * Mathematical and logical operations on arrays.
   * Fourier transforms and routines for shape manipulation.
   * Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

Next, we'll introduce how to use `numpy`. There're no complex concepts, but you need to remember many functions.

### Creating `numpy` arrays

**How to store the coefficients?**

In linear algebra, a system of equations such as
$$ \begin{aligned}
a_{00} x_0 + a_{01} x_1 &= b_0\\
a_{10} x_0 + a_{11} x_1 &= b_1
\end{aligned}$$
is written concisely in *matrix* form as $ \mathbf{A} \mathbf{x} = \mathbf{b} $:
$$ \overbrace{\begin{bmatrix}
a_{00} & a_{01}\\
a_{10} & a_{11}
\end{bmatrix}}^{\mathbf{A}}
\overbrace{
\begin{bmatrix}
x_0\\
x_1
\end{bmatrix}}
^{\mathbf{x}}
= \overbrace{\begin{bmatrix}
b_0\\
b_1
\end{bmatrix}}^{\mathbf{b}},
$$
where
$ \mathbf{A} \mathbf{x}$ is the *matrix multiplication*
$$ \mathbf{A} \mathbf{x} = \begin{bmatrix}
a_{00} x_0 + a_{01} x_1\\
a_{10} x_0 + a_{11} x_1
\end{bmatrix}.$$


We say that $\mathbf{A}$ is a [*matrix*](https://en.wikipedia.org/wiki/Matrix_(mathematics)) and its dimension/shape is $2$-by-$2$:
- The first dimension/axis has size $2$. We also say that the matrix has $2$ rows.
- The second dimension/axis has size $2$. We also say that the matrix has $2$ columns.
$\mathbf{x}$ and $\mathbf{b}$ are called column vectors, which are matrices with one column.

Consider the example
$$ \begin{aligned}
2x_0 + 2x_1 &= 1\\
\hphantom{2x_0 +}  2x_1 &= 1,
\end{aligned}$$
or in matrix form with
$$ \begin{aligned}
\mathbf{A}&=\begin{bmatrix}
a_{00} & a_{01} \\
a_{10} & a_{11} 
\end{bmatrix} 
= \begin{bmatrix}
2 & 2 \\
0 & 2 
\end{bmatrix}\\
\mathbf{b}&=\begin{bmatrix}
b_0\\
b_1
\end{bmatrix} = \begin{bmatrix}
1\\
1
\end{bmatrix}\end{aligned}$$

Instead of using `list` to store the matrix, we will use a `numpy` array.



Numpy array is of data type *ndarray* (n-dimensional array)

* A new data structure created by Numpy—the most important concept in Numpy
* An N-dimensional array is a homogeneous collection of “items”
   * A vector is an array with 1 dimension
      * row vector $[$1    2   3$]$
      * column vector $\left[ \begin{array}{c} 1\\ 5\\ 9 \end{array}\right]$
   * A matrix is an array with 2 dimensions
      * a matrix whose size is 3 $\times$ 4$$\left[ \begin{array}{cccc}
1 & 2 & 3 & 4\\
5 & 6 & 7 & 8 \\
9 & 10 & 11 &12
\end{array} \right] $$

In [173]:
#this example explains how to create a numpy array using array()
import numpy as np
A = np.array([[2.,2],[0,2]])
b = np.array([1.,1])
A, b

(array([[2., 2.],
        [0., 2.]]),
 array([1., 1.]))

Compared to `list`, `numpy` array is often more efficient and has more useful attributes.

In [130]:
#this example shows numpy has more attributes than list
array_attributes = set(attr for attr in dir(np.array([])) if attr[0]!='_')
list_attributes = set(attr for attr in dir(list) if attr[0]!='_')
print('\nCommon attributes:\n',*(array_attributes & list_attributes))
print('\nArray-specific attributes:\n', *(array_attributes - list_attributes))
print('\nList-specific attributes:\n',*(list_attributes - array_attributes))


Common attributes:
 sort copy

Array-specific attributes:
 any tostring newbyteorder itemset shape data size dtype real fill resize view ravel trace partition cumsum itemsize argmax repeat tobytes tolist squeeze swapaxes argsort min ndim flatten byteswap std prod dumps flags searchsorted tofile conj dot astype diagonal clip setflags take setfield put choose dump strides ptp all conjugate mean nbytes imag round argpartition cumprod sum T nonzero flat argmin max compress getfield var item ctypes reshape base transpose

List-specific attributes:
 clear count pop reverse remove extend insert append index


The following attributes give the dimension/shape, number of dimensions, size, and datatype.

In [6]:
for array in A, b:
    print(f'''{array}
    shape: {array.shape}
    ndim: {array.ndim}
    size: {array.size}
    dtype: {array.dtype}
    ''')

[[2. 2.]
 [0. 2.]]
    shape: (2, 2)
    ndim: 2
    size: 4
    dtype: float64
    
[1. 1.]
    shape: (2,)
    ndim: 1
    size: 2
    dtype: float64
    


## Array basic properties

* *ndarray.ndim*: the number of axes (dimensions) of the array
   * In NumPy dimensions are called *axes*
* *ndarray.shape*: Tuple of array dimensions.

* *ndarray.size*: the total number of elements of the array

* *ndarray.dtype*: an object describing the type of the elements in the array

In [132]:
import numpy as np

x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)
print(type(x))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)
12
int64
<class 'numpy.ndarray'>


Note that the function `len` only returns the size of the first dimension:

In [175]:
assert A.shape[0] == len(A)
len(A)

2

Unlike `list`, every `numpy` array has a data type. For efficient computation/storage, numpy implements different data types with different storage sizes:
* integer: `int8`, `int16`, `int32`, `int64`, `uint8`, ...
* float: `float16`, `float32`, `float64`, ...
* complex: `complex64`, `complex128`, ...
* boolean: `bool8`
* Unicode: `string`
* Object: `object`

Specifying your data type
* default data type is floating point (np.float64), you can explicitly specify which data type you want using the *dtype* keyword.

In [135]:
c=np.ones((2,2))  #note the default data type is float64
print(c)
print(c.dtype)

c=np.ones((2,2),dtype=np.int32) #we now use dtype to change it to int32
print(c)
print(c.dtype)

[[1. 1.]
 [1. 1.]]
float64
[[1 1]
 [1 1]]
int32


E.g., `int64` is the 64-bit integer. Unlike `int`, `int64` has a range.

In [8]:
np.int64?
print(f'range: {np.int64(-2**63)} to {np.int64(2**63-1)}')
np.int64(2**63)   # overflow error

range: -9223372036854775808 to 9223372036854775807


OverflowError: Python int too large to convert to C long

We can use the `astype` method to convert the data type:
* more details of `astype` can be found [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html)

In [137]:
print(A)
print(A.dtype)
A_int64 = A.astype(int)       # converts to int64 by default
A_float32 = A.astype(np.float32)  # converts to float32
for array in A_int64, A_float32:
    print(array, array.dtype)

[[2. 2.]
 [0. 2.]]
float64
[[2 2]
 [0 2]] int64
[[2. 2.]
 [0. 2.]] float32


We have to be careful about assigning items of different types to an array.
* Numpy array assumes all the elements have the same data type

In [49]:
A_int64[0,0] = 1
print(A_int64)
A_int64[0,0] = 0.5
print(A_int64)                # intended assignment fails
np.array([int(1), float(1)])  # will be all floating point numbers

[[1 2]
 [0 2]]
[[0 2]
 [0 2]]


array([1., 1.])

**Exercise** Create a heterogeneous numpy array to store both integer and strings:
```Python
[0, 1, 2, 'a', 'b', 'c']
```
*Hint:* There is an numpy data type called `object`.

In [13]:
np.object?
### BEGIN SOLUTION
heterogeneous_np_array = np.array([*range(3),*'abc'],dtype=object)
### END SOLUTION
heterogeneous_np_array

array([0, 1, 2, 'a', 'b', 'c'], dtype=object)

Be careful when creating arrays of `tuple`/`list`:
* the array size will be different if tuple and list are in different sizes

In [12]:
for array in (np.array([(1,2),[3,4,5]],dtype=object),
              np.array([(1,2),[3,4]],dtype=object)):
    print(array, '\nshape:', array.shape, 'length:', len(array), 'size:', array.size)

[(1, 2) list([3, 4, 5])] 
shape: (2,) length: 2 size: 2
[[1 2]
 [3 4]] 
shape: (2, 2) length: 2 size: 4


There are multiple ways to create an array, some common functions are:
* np.zeros(): create an array filled with 0’s
* np.ones(): create an array filled with 1's
* np.eye(): create an array with 1's on the diagonal and 0's elsewhere.
* np.diag(): create a diagonal matrix
* np.empty(): create an array whose initial content is random and depends on the state of the memory
* np.arange(): create an array with a range of elements
* np.linspace(): create an array with values that are spaced linearly in a specified interval
* np.fromfunction(): create an array by executing a function over each coordinate.

In [29]:
np.zeros?
np.zeros(0), np.zeros(1), np.zeros((2,3,4))  # Dimension can be higher than 2

(array([], dtype=float64),
 array([0.]),
 array([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],
 
        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]))

In [21]:
np.ones?
np.ones(0, dtype=int), np.ones((2,3,4), dtype=int)  # initialize values to int 1

(array([], dtype=int64),
 array([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],
 
        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]))

In [19]:
np.eye?
np.eye(0), np.eye(1), np.eye(2), np.eye(3)  # identity matrices

(array([], shape=(0, 0), dtype=float64),
 array([[1.]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [139]:
np.diag?
np.diag(range(1)), np.diag(range(2)), np.diag(range(4)),np.diag(np.ones(3),k=1)  # diagonal matrices

(array([[0]]),
 array([[0, 0],
        [0, 1]]),
 array([[0, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 2, 0],
        [0, 0, 0, 3]]),
 array([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]]))

In [22]:
np.empty?
np.empty(0), np.empty((2,3,4), dtype=int)  # create array faster without initialization

(array([], dtype=float64),
 array([[[      94670546641504,       94670546936976,
            112699271858381412,   112701470881637476],
         [  112703669904893540,   112705868928149604,
            112708067951405668,   112710266974661732],
         [  112712465997917796,   112714665021173860,
            112716864044429924,   112719063067685988]],
 
        [[  112721262090942052,   112723461114198116,
            112725660137454180,   112727859160710244],
         [  112730058183966308,   112732257207222372,
            112734456230478436,   112736655253734500],
         [-8762877256829074840,   673851663452471696,
          -8546704472567185008, -8474646880643841916]]]))

`numpy` also provides functions to build an array using rules.

In [24]:
np.arange?
np.arange(5), np.arange(4,5), np.arange(4.5,5.5,0.5)  # like range but allow non-integer parameters

(array([0, 1, 2, 3, 4]), array([4]), array([4.5, 5. ]))

In [176]:
np.linspace?
np.linspace(4,5), np.linspace(4,5,11), np.linspace(4,5,20)  # can specify number of points instead of step
#np.linspace(4,5) will create an array with 50 elements
#np.linspace(4,5,11) will create an array with 11 elements
#np.linspace(4,5,20) will create an array with 20 elements
#the shape is determined automatically

(array([4.        , 4.02040816, 4.04081633, 4.06122449, 4.08163265,
        4.10204082, 4.12244898, 4.14285714, 4.16326531, 4.18367347,
        4.20408163, 4.2244898 , 4.24489796, 4.26530612, 4.28571429,
        4.30612245, 4.32653061, 4.34693878, 4.36734694, 4.3877551 ,
        4.40816327, 4.42857143, 4.44897959, 4.46938776, 4.48979592,
        4.51020408, 4.53061224, 4.55102041, 4.57142857, 4.59183673,
        4.6122449 , 4.63265306, 4.65306122, 4.67346939, 4.69387755,
        4.71428571, 4.73469388, 4.75510204, 4.7755102 , 4.79591837,
        4.81632653, 4.83673469, 4.85714286, 4.87755102, 4.89795918,
        4.91836735, 4.93877551, 4.95918367, 4.97959184, 5.        ]),
 array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ]),
 array([4.        , 4.05263158, 4.10526316, 4.15789474, 4.21052632,
        4.26315789, 4.31578947, 4.36842105, 4.42105263, 4.47368421,
        4.52631579, 4.57894737, 4.63157895, 4.68421053, 4.73684211,
        4.78947368, 4.84210526, 4.89473684, 4.947

In [120]:
np.fromfunction?
print(np.fromfunction(lambda i, j: i * j, (3,4)))  # can initialize using a function
#the above code will generate an array with size (3,4), and each element is calculated by i*j

#equivalent to the code below
def f(i,j):
    return i*j

print(np.fromfunction(f,(3,4)))


#it will create a 3*4 array, the element of Ai,j is determined by i*j
#[0*0 0*1 0*2 0*3
# 1*0 1*1 1*2 1*3
# 2*0 2*1 2*2 2*3]

[[0. 0. 0. 0.]
 [0. 1. 2. 3.]
 [0. 2. 4. 6.]]
[[0. 0. 0. 0.]
 [0. 1. 2. 3.]
 [0. 2. 4. 6.]]


We can also reshape an array using the `reshape` method/function:
* syntax: numpy.reshape(a, newshape, order='C')
* Reshaping means changing the shape of an array.
* You are allowed to have one "unknown" dimension.
   * Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
   * Pass `-1` as the value, and NumPy will calculate this number for you.
* you can change the order of elements by specifying order: order='C' or order ='F'
* More information can be found [here](https://www.w3resource.com/numpy/manipulation/reshape.php)

In [39]:
array = np.arange(2*3*4)
array.reshape?
(array, 
 array.reshape(2,3,4),      # last axis index changes fastest
 array.reshape(2,3,-1),     # size of last axis calculated automatically
 array.reshape((2,3,4), order='F')) # first axis index changes fastest

#the example below shows the difference of order='C' and order='F'
#x = np.array([[1,2,3], [4,5,6]])
#print(x)
#print(np.reshape(x, 6, order='F')) 
#print(np.reshape(x, 6, order='C')) 

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([[[ 0,  6, 12, 18],
         [ 2,  8, 14, 20],
         [ 4, 10, 16, 22]],
 
        [[ 1,  7, 13, 19],
         [ 3,  9, 15, 21],
         [ 5, 11, 17, 23]]]))

`flatten` is a special case of reshaping an array to one dimension.
* syntax: ndarray.flatten(order='C')
* The flatten() function is used to get a copy of an given array collapsed into one dimension.
* More information can be found [here](https://www.w3resource.com/numpy/manipulation/ndarray-flatten.php)

In [38]:
array = np.arange(2*3*4).reshape(2,3,4)
array, array.flatten(), array.reshape(-1), array.flatten(order='F')

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0, 12,  4, 16,  8, 20,  1, 13,  5, 17,  9, 21,  2, 14,  6, 18, 10,
        22,  3, 15,  7, 19, 11, 23]))

**Exercise** Correct the following function to print every element of an array line-by-line.
```Python
def print_array_entries_line_by_line(array):
    for i in array:
        print(i)
```

In [177]:
def print_array_entries_line_by_line(array):
    ### BEGIN SOLUTION
    for i in array.flatten():
        print(i)
    ### END SOLUTION
    
print_array_entries_line_by_line(np.arange(2*3*4).reshape(2,3,4))

#the following is the wrong implementation
def print_array_entries_line_by_line_wrong(array):
    for i in array:
        print(i)
        
#print_array_entries_line_by_line_wrong(np.arange(2*3*4).reshape(2,3,4))

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


Let's have a short break.

### Operating on `numpy` arrays

**Arithmetic operations are element-wise!**

* Addition: a+b or np.add(a,b)
* Subtraction: a-b or np.subtract(a,b)
* Multiplication: a*b or np.multiply(a,b)
* Division: a/b or np.divide(a,b)

**So how about matrix multiplication?**
* We use @ or np.matmul(): a@b or np.matmul(a,b)

In [50]:
import numpy as np
x = np.array([[1, 2],[3,4]])
y = np.array([[5, 6], [7, 8]])

print(x)
print(y)

print("Addition:")
print(x+y)
print(np.add(x,y))

print("Subtraction:")
print(x-y)
print(np.subtract(x,y))

print("Arithmetic multiplication:")
print(x*y)
print(np.multiply(x,y))

print("Matrix multiplication:")
print(x@y)
print(np.matmul(x,y))

print("Arithmetic division:")
print(x/y)
print(np.divide(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Addition:
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
Subtraction:
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
Arithmetic multiplication:
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
Arithmetic division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**How to verify the solution of a system of linear equations?**

Before solving the system of linear equations, let us try to verify a solution to the equations:
$$ \begin{aligned}
2x_0 + 2x_1 &= 1\\
\hphantom{2x_0 +}  2x_1 &= 1
\end{aligned}$$

`numpy` provides the function `matmul` and the operator `@` for matrix multiplication.

In [143]:
print(np.matmul(A,np.array([0,0])) == b) #x0=0, x1=0 is wrong solution
print(A @ np.array([0,0.5]) == b)   #x0=0, x1=0.5 is correct solution

[False False]
[ True  True]


Note that the comparison on `numpy` arrays returns a boolean array instead of a boolean value, unlike the comparison operations on lists.

To check whether all items are true, we use the `all` method.

In [55]:
print((np.matmul(A,np.array([0,0])) == b).all())
print((A @ np.array([0,0.5]) == b).all())

False
True


**How to concatenate arrays?**

We will operate on an augmented matrix of the coefficients:
$$ \begin{aligned} \mathbf{C} &= \begin{bmatrix}
\mathbf{A} & \mathbf{b}
\end{bmatrix}\\
&= \begin{bmatrix}
a_{00} & a_{01} & b_0 \\
a_{10} & a_{11} & b_1
\end{bmatrix} 
\end{aligned}
$$


`numpy` provides functions to create block matrices:

In [144]:
np.block?
C = np.block([A,b.reshape(-1,1)])  # reshape to ensure same ndim
#b.reshape(-1,1) because we don't know the size of the first dimention, we want the system to calculate automatically for us
print(A)
print(b)
print(b.reshape(-1,1))           
print(C)

[[2. 2.]
 [0. 2.]]
[1. 1.]
[[1.]
 [1.]]
[[2. 2. 1.]
 [0. 2. 1.]]


To stack an array along different axes:
   * hstack(): Stacks arrays in sequence horizontally (column wise)[more information](https://www.w3resource.com/numpy/manipulation/hstack.php)
   * vstack(): Stacks arrays in sequence vertically (row wise) [more information](https://www.w3resource.com/numpy/manipulation/vstack.php)
   * concatenate(): returns an ndarray of the provided type that satisfies requirements. [more information](https://www.w3resource.com/numpy/manipulation/concatenate.php)
   * stack(): used to join a sequence of arrays along a new axis.
      * it will create a new axis, so it will change the shape of original arrays.
      * [more information](https://www.w3resource.com/numpy/manipulation/stack.php)

In [116]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print('x:')
print(x)
print('y:')
print(y)

print('Vertical stack:')
z=np.vstack((x,y))
print(z)
print(z.shape)

print('Horizontal stack:')
z=np.hstack((x,y))
print(z)
print(z.shape)

print('Concatenate:')
z=np.concatenate((x,y))
print(z)


print('Stack, axis=0:')
z=np.stack((x,y),axis=0)
print(z)
print(z.shape)

print('stack, axis=1:')
z=np.stack((x,y),axis=1)
print(z)
print(z.shape)

x:
[1 2 3]
y:
[4 5 6]
Vertical stack:
[[1 2 3]
 [4 5 6]]
(2, 3)
Horizontal stack:
[1 2 3 4 5 6]
(6,)
Concatenate:
[1 2 3 4 5 6]
Stack, axis=0:
[[1 2 3]
 [4 5 6]]
(2, 3)
stack, axis=1:
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [58]:
#this is another example showing how to use hstack(), vstack(), concatenate() and stack()
array = np.arange(1*2*3).reshape(1,2,3)
for concat_array in [array,
                     np.hstack((array,array)),   # stack along the first axis
                     np.vstack((array,array)),                  # second axis
                     np.concatenate((array,array), axis=-1),    # last axis
                     np.stack((array,array), axis=0)]:          # new axis
    print(concat_array, '\nshape:', concat_array.shape)

[[[0 1 2]
  [3 4 5]]] 
shape: (1, 2, 3)
[[[0 1 2]
  [3 4 5]
  [0 1 2]
  [3 4 5]]] 
shape: (1, 4, 3)
[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]] 
shape: (2, 2, 3)
[[[0 1 2 0 1 2]
  [3 4 5 3 4 5]]] 
shape: (1, 2, 6)
[[[[0 1 2]
   [3 4 5]]]


 [[[0 1 2]
   [3 4 5]]]] 
shape: (2, 1, 2, 3)


**How to perform arithmetic operations on a `numpy` array?**

To divide all the coefficients by $2$, we can simply write:

In [145]:
D = C / 2
D

array([[1. , 1. , 0.5],
       [0. , 1. , 0.5]])

Note that the above does not work for `list`.

In [69]:
C.tolist() / 2 # deep convert to list

TypeError: unsupported operand type(s) for /: 'list' and 'int'

Arithmetic operations on `numpy` arrays apply if the arrays have compatible dimensions. Two dimensions are compatible when
- they are equal, except for
- components equal to 1.

**Broadcasting**

* Arithmetic operations on arrays are usually done on corresponding elements. 
   * If two arrays are of exactly the same shape, it's ok
   * what happens if the shape of two arrays are different?
* The term *broadcasting* describes how Numpy treats arrays with different shapes during arithmetic operations
* The following program shows an example of broadcasting

In [71]:
a = np.array([[ 0.0, 0.0, 0.0],[10.0,10.0,10.0],
[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
print('First array:')
print(a)
print('\n')
print('Second array:')
print(b)
print('\n')
print('First Array + Second Array')
print(a+b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


`numpy` uses [broadcasting rules](https://numpy.org/doc/stable/user/basics.broadcasting.html#general-broadcasting-rules) to stretch the axis of size 1 up to match the corresponding axis in other arrays.  
`C / 2` is a example where the second operand $2$ is broadcasted to a $2$-by-$2$ matrix before the elementwise division. Another example is follows. 

In [70]:
three_by_one = np.arange(3).reshape(3,1)
one_by_four = np.arange(4).reshape(1,4)
print(f'''
{three_by_one}
*
{one_by_four}
==
{three_by_one * one_by_four}
''')


[[0]
 [1]
 [2]]
*
[[0 1 2 3]]
==
[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]]



Next, we introduce array indexing

e.g., to subtract the second row of the coefficients from the first row:

In [180]:
D[0,:] = D[0,:] - D[1,:]
D

NameError: name 'D' is not defined

Notice the use of commas to index different dimensions instead of using multiple brackets:

In [179]:
assert (D[0][:] == D[0,:]).all()

#they're equivalent
print(D[0][:])
print(D[0,:])

NameError: name 'D' is not defined

Using this indexing technique, it is easy extract the last column as the solution to the system of linear equations:

In [178]:
print(D)
x = D[:,-1]
print(x)

NameError: name 'D' is not defined

This gives the desired solution $x_0=0$ and $x_1=0.5$ for
$$ \begin{aligned}
2x_0 + 2x_1 &= 1\\
\hphantom{2x_0 +}  2x_1 &= 1\\
\end{aligned}$$

`numpy` provides many [convenient ways](https://numpy.org/doc/stable/reference/arrays.indexing.html#advanced-indexing) to index an array.

In [148]:
B = np.arange(2*3).reshape(2,3)
B, B[(0,1),(2,0)]  # selecting the corners using integer array

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([2, 3]))

In [169]:
#B = np.arange(2*3*4).reshape(2,3,4)
B=np.array([[[1,4,7],[2,9,7],[1,3,0],[9,6,9]],[[2,3,4],[3,4,5],[0,1,2],[6,7,8]]])
B, B[0], B[0,(1,2)], B[0,(1,2),(2,2)], B[:,(1,2),(2,2)]  # pay attention to the last two cases
#B[0,(1,2),(2,2)] will operate on the first dimention (axis 0)
#B[:,(1,2),(2,2)] will operate on all the dimentions (2 in this example)

(array([[[1, 4, 7],
         [2, 9, 7],
         [1, 3, 0],
         [9, 6, 9]],
 
        [[2, 3, 4],
         [3, 4, 5],
         [0, 1, 2],
         [6, 7, 8]]]),
 array([[1, 4, 7],
        [2, 9, 7],
        [1, 3, 0],
        [9, 6, 9]]),
 array([[2, 9, 7],
        [1, 3, 0]]),
 array([7, 0]),
 array([[7, 0],
        [5, 2]]))

The ellipsis ... (three dots) indicates "as many ':' as needed".

In [153]:
x=np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
print(x)
#x[...,1] is equivalent to x[:,1]
x[...,1]  # ... expands to selecting all elements of all previous dimensions

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 5, 8])

In [183]:
import numpy as np
x=np.array([1, 2, 3, 4, 5, 6, 7])
x[x>5]  # indexing using boolean array

array([6, 7])

Finally, the following function solves a system of 2 linear equations with 2 variables.

In [184]:
def solve_2_by_2_system(A,b):
    '''Returns the unique solution of the linear system, if exists, 
    else returns None.'''
    C = np.hstack((A,b.reshape(-1,1)))
    if C[0,0] == 0: C = C[(1,0),:]
    if C[0,0] == 0: return None
    C[0,:] = C[0,:] / C[0,0]
    C[1,:] = C[1,:] - C[0,:] * C[1,0]
    if C[1,1] == 0: return None
    C[1,:] = C[1,:] / C[1,1]
    C[0,:] = C[0,:] - C[1,:] * C[0,1]
    return C[:,-1]

In [155]:
# tests
for A in (np.eye(2),
          np.ones((2,2)),
          np.stack((np.ones(2),np.zeros(2))),
          np.stack((np.ones(2),np.zeros(2)),axis=1)):
    print(f'A={A}\nb={b}\nx={solve_2_by_2_system(A,b)}\n')

A=[[1. 0.]
 [0. 1.]]
b=[1. 1.]
x=[1. 1.]

A=[[1. 1.]
 [1. 1.]]
b=[1. 1.]
x=None

A=[[1. 1.]
 [0. 0.]]
b=[1. 1.]
x=None

A=[[1. 0.]
 [1. 0.]]
b=[1. 1.]
x=None



### Universal functions

A universal function (or *ufunc* for short) is a function that operates on ndarrays in an element-by-element fashion
* NumPy provides familiar mathematical functions, such as
   * *np.exp* : $e^x$, where $e=2.718281$ (also called Euler's number)
   * *np.sqrt*
   * *np.sin*
   * *np.cos*
* Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [87]:
import numpy as np
a = np.array([[1, 2, 3],[4,5,6]])
print('a:')
print(a)
print('exp(a):')
print(np.exp(a))
print('square root of a:')
print(np.sqrt(a))
print('sin(a):')
print(np.sin(a))
print('cos(a):')
print(np.cos(a))

a:
[[1 2 3]
 [4 5 6]]
exp(a):
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
square root of a:
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
sin(a):
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
cos(a):
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]


Why does the first line of code below return two arrays but the second code return only one array? Shouldn't the first line of code return the following?
```Python
array([[(0,1), (0,2), (0,3)],
       [(1,1), (1,2), (1,3)]])
```

In [161]:
print(np.fromfunction(lambda i,j:(i,j), (2,3), dtype=int))
print(np.fromfunction(lambda i,j:(i*j), (2,3), dtype=int))


#print(np.fromfunction(f1, (2,3), dtype=int))

#lambda i,j:(i,j) is equivalent to the following function
def f1(i,j):
    return (i,j)  #it returns a tuple

f1(array1,array2)
#because the shape is (2,3), so i and j are:
i=np.array([[0, 0 ,0],
   [1, 1, 1]])
j=np.array([[0, 1, 2],
   [0, 1, 2],
   [0, 1, 2]])

#the function will use i and j (bot are arrays) as argument
result1 = f1(i,j)
print(result1)

(array([[0, 0, 0],
       [1, 1, 1]]), array([[0, 1, 2],
       [0, 1, 2]]))
[[0 0 0]
 [0 1 2]]
(array([[0, 0, 0],
       [1, 1, 1]]), array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]]))


From the documentation, `fromfunction` applies the given function to the two arrays as arguments.
- The first line of code returns a tuple of the arrays.
- The second line of code multiply the two arrays to give one array, according to how multiplication works for numpy arrays.

Indeed, `numpy` implements [universal/vectorized functions/operators](https://numpy.org/doc/stable/reference/ufuncs.html) that takes arrays as arguments and perform operations with appropriate broadcasting rules. The following is an example that uses the universal function `np.sin`:

In [162]:
import matplotlib.pyplot as plt

@widgets.interact(a=(0,5,1),b=(-1,1,0.1))
def plot_sin(a=1,b=0):
    x = np.linspace(0,2*math.pi)
    plt.plot(x,np.sin(a*x+b*math.pi))  # np.sin, *, + are universal functions
    plt.title(r'$\sin(ax+b\pi)$')
    plt.xlabel(r'$x$ (radian)')

interactive(children=(IntSlider(value=1, description='a', max=5), FloatSlider(value=0.0, description='b', max=…

In addition to making the code shorter, universal functions are both efficient and flexible. (Recall the Monte Carlo simulation to approximate $\pi$.)

**Exercise** Explain how the Monte Carlo simulation work using universal functions:
```Python
def np_approximate_pi(n):
    in_circle = (np.random.random((n,2))**2).sum(axis=-1) < 1
    mean = 4 * in_circle.mean()
    std = 4 * in_circle.std() / n**0.5
    return np.array([mean - 2*std, mean + 2*std])
```

- `random.random` generates a numpy array for $n$ points in the unit square randomly.
- `sum` sums up the element along the last axis to give the squared distance.
- `<` returns the boolean array indicating whether each point is in the first quadrant of the inscribed circle.
- `mean` and `std` returns the mean and standard deviation of the boolean array with True and False interpreted as 1 and 0 respectively.

In [11]:
def is_prime(n):
    if n==2:
        return True
    if n<2 or n%2==0:
        return False
    factor=3
    root=n**0.5
    while factor<=root:
        if n%factor==0:
            return False
        factor+=2
    return True

def prime_sequence(stop):
    for i in range(stop+1):
        if is_prime(i):
            yield i
            
print(*prime_sequence(50))

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47


In [ ]:
2 3 5 7 11 13 17 19 23 29 31 37 41 43 47